(PRCHSR_ORG_NBR, RLTD_PRCHSR_ORG_NBR, prod_id, BNFT_PKG_ID, PKG_NBR, MBRSHP_SOR_CD, RLTD_PRCHSR_ORG_TYPE_CD, PROD_SOR_CD, ELGBLTY_CLNDR_MNTH_END_DT, MBR_KEY, BNFT_PKG_KEY, MBR_PROD_ENRLMNT_EFCTV_DT, MAX_FUNDG_CF_CD ,FUNDG_CF_CD ,src_grp_nbr ,mdcl_mbr_cvrg_cnt ,vsn_mbr_cnt ,dntl_mbr_cnt ,mbr_prod_enrlmnt_trmntn_dt ,cntrct_type_cd ,othr_insrnc_type_cd ,gndr_cd ,mbr_mnth_cob_cd ,prcp_id ,prcp_ctgry_cd ,prcp_type_cd ,hc_id ,sbscrbr_id ,scrty_lvl_cd ,prod_ofrg_key ,mdcl_expsr_nbr ,phrmcy_mbr_expsr_nbr ,dntl_expsr_nbr ,vsn_expsr_nbr ,PHRMCY_MBR_CVRG_CNT ,MBU_CF_CD ,CDHP_CTGRY_CD ,cii_rmm_flg);

where(trim(RCRD_STTS_CD)!=DEL);

(trim(PRCHSR_ORG_CTGRY_TYPE_CD)as(PRCHSR_ORG_CTGRY_TYPE_CD), trim(MBRSHP_SOR_CD)as(MBRSHP_SOR_CD), trim(PRCHSR_ORG_NBR)as(PRCHSR_ORG_NBR), trim(PRCHSR_ORG_TYPE_CD)as(PRCHSR_ORG_TYPE_CD), RCRD_STTS_CD );

DMGPRCHSR_ORG_TYPE_CD,left_outer);

( FLTRPRCHSR_ORG_NBR ,FLTRRLTD_PRCHSR_ORG_NBR ,FLTRprod_id ,FLTRBNFT_PKG_ID ,FLTRPKG_NBR ,FLTRMBRSHP_SOR_CD ,FLTRRLTD_PRCHSR_ORG_TYPE_CD ,FLTRPROD_SOR_CD ,FLTRELGBLTY_CLNDR_MNTH_END_DT ,FLTRMBR_KEY ,FLTRBNFT_PKG_KEY ,FLTRMBR_PROD_ENRLMNT_EFCTV_DT ,DMGPRCHSR_ORG_CTGRY_TYPE_CD ,DMGPRCHSR_ORG_TYPE_CD ,DMGRCRD_STTS_CD ,SGMNTN_SUBGRP_ID ,prod_id1 ,SGMNTN_SOR_CD ,GRP_STTS_CD,MAX_FUNDG_CF_CD ,GRP_PLAN_CD ,FLTRFUNDG_CF_CD ,FLTRsrc_grp_nbr ,FLTRmdcl_mbr_cvrg_cnt ,FLTRvsn_mbr_cnt ,FLTRdntl_mbr_cnt ,FLTRmbr_prod_enrlmnt_trmntn_dt ,FLTRcntrct_type_cd ,FLTRothr_insrnc_type_cd ,FLTRgndr_cd ,FLTRmbr_mnth_cob_cd ,FLTRprcp_id ,FLTRprcp_ctgry_cd ,FLTRprcp_type_cd ,FLTRhc_id ,FLTRsbscrbr_id ,FLTRscrty_lvl_cd ,FLTRprod_ofrg_key ,FLTRmdcl_expsr_nbr ,FLTRphrmcy_mbr_expsr_nbr ,FLTRdntl_expsr_nbr ,FLTRvsn_expsr_nbr ,FLTRPHRMCY_MBR_CVRG_CNT ,FLTRMBU_CF_CD ,CDHP_CTGRY_CD ,FLTRCII_RMM_FLG);

//(PROD_OFRG_KEY,PROD_OFRG_NTWK_EFCTV_DT,PROD_OFRG_NTWK_TRMNTN_DT,MAX_NTWK_IDas(NTWK_ID));

INTRM_PRODCTMBRSHP_SOR_CD , left_outer);

join(WRK_ECR_SCD_PRODas(WRK_ECR_SCD_PROD),trim(FLTRPROD_ID)==WRK_ECR_SCD_PRODPROD_ID && FLTRPROD_SOR_CD==WRK_ECR_SCD_PRODPROD_SOR_CD , left_outer);

join(PROD_OFRG_NTWKas(PROD_OFRG_NTWK),trim(FLTRPROD_OFRG_KEY)==PROD_OFRG_NTWKPROD_OFRG_KEY && FLTRELGBLTY_CLNDR_MNTH_END_DT==PROD_OFRG_NTWKNTWK_DT , left_outer);

( FLTRPRCHSR_ORG_NBR ,FLTRRLTD_PRCHSR_ORG_NBR ,FLTRprod_id ,FLTRBNFT_PKG_ID ,FLTRPKG_NBR ,FLTRMBRSHP_SOR_CD ,FLTRRLTD_PRCHSR_ORG_TYPE_CD ,FLTRPROD_SOR_CD ,FLTRELGBLTY_CLNDR_MNTH_END_DT ,FLTRMBR_KEY ,FLTRBNFT_PKG_KEY ,FLTRMBR_PROD_ENRLMNT_EFCTV_DT ,PRCHSR_ORG_CTGRY_TYPE_CD ,PRCHSR_ORG_TYPE_CD ,RCRD_STTS_CD ,SGMNTN_SUBGRP_ID ,prod_id1 ,SGMNTN_SOR_CD ,GRP_STTS_CD ,MAX_FUNDG_CF_CD ,FLTRGRP_PLAN_CD ,FLTRFUNDG_CF_CD ,FLTRsrc_grp_nbr ,FLTRmdcl_mbr_cvrg_cnt ,FLTRvsn_mbr_cnt ,FLTRdntl_mbr_cnt ,FLTRmbr_prod_enrlmnt_trmntn_dt ,FLTRcntrct_type_cd ,FLTRothr_insrnc_type_cd ,FLTRgndr_cd ,FLTRmbr_mnth_cob_cd ,FLTRprcp_id ,FLTRprcp_ctgry_cd ,FLTRprcp_type_cd ,FLTRhc_id ,FLTRsbscrbr_id ,FLTRscrty_lvl_cd ,FLTRprod_ofrg_key ,FLTRmdcl_expsr_nbr ,FLTRphrmcy_mbr_expsr_nbr ,FLTRdntl_expsr_nbr ,FLTRvsn_expsr_nbr ,FLTRPHRMCY_MBR_CVRG_CNT ,FLTRMBU_CF_CD ,PLAN_GRP_ID ,CDHP_CTGRY_CD1as(CDHP_CTGRY_CD);

PLRFSOR_CD,left_outer);

join(WRK_PRODas(WPRD),F1GRP_PLAN_CD== WPRDGRP_PLAN_CD && F1MBRSHP_SOR_CD== WPRDMBRSHP_SOR_CD,left_outer);

join(df_prdas(prd),F1PROD_SOR_CD== prdPROD_SOR_CD && F1PROD_ID == prdPROD_ID ,left_outer);

( F1PRCHSR_ORG_NBR ,F1RLTD_PRCHSR_ORG_NBR ,F1prod_id ,F1BNFT_PKG_ID ,F1PKG_NBR ,F1MBRSHP_SOR_CD ,F1RLTD_PRCHSR_ORG_TYPE_CD ,F1PROD_SOR_CD ,F1ELGBLTY_CLNDR_MNTH_END_DT ,F1MBR_KEY ,F1BNFT_PKG_KEY ,F1MBR_PROD_ENRLMNT_EFCTV_DT ,F1PRCHSR_ORG_CTGRY_TYPE_CD ,F1PRCHSR_ORG_TYPE_CD ,F1RCRD_STTS_CD ,F1SGMNTN_SUBGRP_ID ,F1prod_id1 ,F1SGMNTN_SOR_CD ,F1GRP_STTS_CD ,when(HLTH_PROD_SRVC_TYPE_CD1isin(,~01,~02,~03,~NA,~DV,UNK),NA)otherwise(HLTH_PROD_SRVC_TYPE_CD1)as(HLTH_PROD_SRVC_TYPE_CD);

DPTELGBLTY_CLNDR_MNTH_END_DT,left_outer);

( FLTRPRCHSR_ORG_NBR ,FLTRRLTD_PRCHSR_ORG_NBR ,FLTRprod_id ,FLTRBNFT_PKG_ID ,FLTRPKG_NBR ,FLTRMBRSHP_SOR_CD ,FLTRRLTD_PRCHSR_ORG_TYPE_CD ,FLTRPROD_SOR_CD ,FLTRELGBLTY_CLNDR_MNTH_END_DT ,FLTRMBR_KEY ,FLTRBNFT_PKG_KEY ,FLTRMBR_PROD_ENRLMNT_EFCTV_DT ,FLTRPRCHSR_ORG_CTGRY_TYPE_CD ,FLTRPRCHSR_ORG_TYPE_CD ,FLTRRCRD_STTS_CD ,FLTRSGMNTN_SUBGRP_ID ,FLTRprod_id1 ,FLTRSGMNTN_SOR_CD ,FLTRGRP_STTS_CD ,FLTRHLTH_PROD_SRVC_TYPE_CD ,FLTRPLAN_ID1 ,trim(EMPLR_DEPT_NBR)as(EMPLR_DEPT_NBR);

RLSHPELGBLTY_CLNDR_MNTH_END_DT ,left_outer);

( FLTRPRCHSR_ORG_NBR ,FLTRRLTD_PRCHSR_ORG_NBR ,FLTRprod_id ,FLTRBNFT_PKG_ID ,FLTRPKG_NBR ,FLTRMBRSHP_SOR_CD ,FLTRRLTD_PRCHSR_ORG_TYPE_CD ,FLTRPROD_SOR_CD ,FLTRELGBLTY_CLNDR_MNTH_END_DT ,FLTRMBR_KEY ,FLTRBNFT_PKG_KEY ,FLTRMBR_PROD_ENRLMNT_EFCTV_DT ,FLTRPRCHSR_ORG_CTGRY_TYPE_CD ,FLTRPRCHSR_ORG_TYPE_CD ,FLTRRCRD_STTS_CD ,FLTRSGMNTN_SUBGRP_ID ,FLTRprod_id1 ,FLTRSGMNTN_SOR_CD ,FLTRGRP_STTS_CD ,FLTRHLTH_PROD_SRVC_TYPE_CD ,FLTRPLAN_ID1 ,FLTREMPLR_DEPT_NBR ,FLTRMAX_FUNDG_CF_CD ,SGMNTN_ASSN_ID ,FLTRFUNDG_CF_CD ,FLTRsrc_grp_nbr ,FLTRmdcl_mbr_cvrg_cnt ,FLTRvsn_mbr_cnt ,FLTRdntl_mbr_cnt ,FLTRmbr_prod_enrlmnt_trmntn_dt ,FLTRcntrct_type_cd ,FLTRothr_insrnc_type_cd ,FLTRgndr_cd ,FLTRmbr_mnth_cob_cd ,FLTRprcp_id ,FLTRprcp_ctgry_cd ,FLTRprcp_type_cd ,FLTRhc_id ,FLTRsbscrbr_id ,FLTRscrty_lvl_cd ,FLTRprod_ofrg_key ,FLTRmdcl_expsr_nbr ,FLTRphrmcy_mbr_expsr_nbr ,FLTRdntl_expsr_nbr ,FLTRvsn_expsr_nbr ,FLTRPHRMCY_MBR_CVRG_CNT ,FLTRRX_OVERRIDE_FLAG ,FLTRORIG_HLTH_PROD_SRVC_TYPE_CD ,FLTRMBU_CF_CD ,FLTRCLM_CD ,FLTRCLM_RPTG_1_CD ,FLTRCLM_RPTG_2_CD ,FLTRCLM_RPTG_3_CD ,FLTREMP_NBR ,FLTRPLAN_GRP_ID ,FLTRCDHP_CTGRY_CD ,FLTRMBR_NTWK_ID ,FLTRCII_RMM_FLG );

join(df_rlshp2as(RLSHP2), FLTRMBRSHP_SOR_CD == RLSHP2MBRSHP_SOR_CD && FLTRPRCHSR_ORG_NBR == RLSHP2RLTD_PRCHSR_ORG_NBR && FLTRELGBLTY_CLNDR_MNTH_END_DT == RLSHP2ELGBLTY_CLNDR_MNTH_END_DT ,left_outer);

( FLTRPRCHSR_ORG_NBR ,FLTRRLTD_PRCHSR_ORG_NBR ,FLTRprod_id ,FLTRBNFT_PKG_ID ,FLTRPKG_NBR ,FLTRMBRSHP_SOR_CD ,FLTRRLTD_PRCHSR_ORG_TYPE_CD ,FLTRPROD_SOR_CD ,FLTRELGBLTY_CLNDR_MNTH_END_DT ,FLTRMBR_KEY ,FLTRBNFT_PKG_KEY ,FLTRMBR_PROD_ENRLMNT_EFCTV_DT ,FLTRPRCHSR_ORG_CTGRY_TYPE_CD ,FLTRPRCHSR_ORG_TYPE_CD ,FLTRRCRD_STTS_CD ,FLTRSGMNTN_SUBGRP_ID ,FLTRprod_id1 ,FLTRSGMNTN_SOR_CD ,FLTRGRP_STTS_CD ,FLTRHLTH_PROD_SRVC_TYPE_CD ,FLTRPLAN_ID1 ,FLTREMPLR_DEPT_NBR ,FLTRMAX_FUNDG_CF_CD ,SGMNTN_ASSN_ID ,SGMNTN_CLNT_ID ,FLTRFUNDG_CF_CD ,FLTRsrc_grp_nbr ,FLTRmdcl_mbr_cvrg_cnt ,FLTRvsn_mbr_cnt ,FLTRdntl_mbr_cnt ,FLTRmbr_prod_enrlmnt_trmntn_dt ,FLTRcntrct_type_cd ,FLTRothr_insrnc_type_cd ,FLTRgndr_cd ,FLTRmbr_mnth_cob_cd ,FLTRprcp_id ,FLTRprcp_ctgry_cd ,FLTRprcp_type_cd ,FLTRhc_id ,FLTRsbscrbr_id ,FLTRscrty_lvl_cd ,FLTRprod_ofrg_key ,FLTRmdcl_expsr_nbr ,FLTRphrmcy_mbr_expsr_nbr ,FLTRdntl_expsr_nbr ,FLTRvsn_expsr_nbr ,FLTRPHRMCY_MBR_CVRG_CNT ,FLTRRX_OVERRIDE_FLAG ,FLTRORIG_HLTH_PROD_SRVC_TYPE_CD ,FLTRMBU_CF_CD ,FLTRCLM_CD ,FLTRCLM_RPTG_1_CD ,FLTRCLM_RPTG_2_CD ,FLTRCLM_RPTG_3_CD ,FLTREMP_NBR ,FLTRPLAN_GRP_ID ,FLTRCDHP_CTGRY_CD ,FLTRMBR_NTWK_ID ,FLTRCII_RMM_FLG );

FLT1MAX_FUNDG_CF_CD ,left_outer);

( upper(FLT1PRCHSR_ORG_NBR)as(SGMNTN_GRP_ID);

CIIUtilitiesreadDFfromS3(aDataSrcCfg,df_mbr_cob);

cob_dataLAST_DT_OF_THE_MNTH_DT , left_outer);

( FLT1SGMNTN_GRP_ID ,FLT1RLTD_PRCHSR_ORG_NBR ,FLT1prod_id ,FLT1BNFT_PKG_ID ,FLT1PLAN_ID ,FLT1PKG_NBR ,FLT1MBRSHP_SOR_CD ,FLT1RLTD_PRCHSR_ORG_TYPE_CD ,FLT1PROD_SOR_CD ,FLT1ELGBLTY_CLNDR_MNTH_END_DT ,FLT1MBR_KEY ,FLT1BNFT_PKG_KEY ,FLT1MBR_PROD_ENRLMNT_EFCTV_DT ,FLT1SGMNTN_SUBGRP_ID ,FLT1prod_id1 ,FLT1SGMNTN_SOR_CD ,FLT1GRP_STTS_CD ,FLT1HLTH_PROD_SRVC_TYPE_CD ,FLT1EMPLR_DEPT_NBR ,FLT1MAX_FUNDG_CF_CD ,FLT1SGMNTN_ASSN_ID ,FLT1SGMNTN_CLNT_ID ,FULLY_INSRD_CD ,FLT1FUNDG_CF_CD ,FLT1src_grp_nbr ,FLT1mdcl_mbr_cvrg_cnt ,FLT1vsn_mbr_cnt ,FLT1dntl_mbr_cnt ,FLT1mbr_prod_enrlmnt_trmntn_dt ,FLT1cntrct_type_cd ,FLT1othr_insrnc_type_cd ,FLT1gndr_cd ,FLT1mbr_mnth_cob_cd ,FLT1prcp_id ,FLT1prcp_ctgry_cd ,FLT1prcp_type_cd ,FLT1hc_id ,FLT1sbscrbr_id ,FLT1scrty_lvl_cd ,FLT1prod_ofrg_key ,FLT1mdcl_expsr_nbr ,FLT1phrmcy_mbr_expsr_nbr ,FLT1dntl_expsr_nbr ,FLT1vsn_expsr_nbr ,FLT1PHRMCY_MBR_CVRG_CNT ,FLT1RX_OVERRIDE_FLAG ,FLT1ORIG_HLTH_PROD_SRVC_TYPE_CD ,FLT1MBU_CF_CD ,FLT1CLM_CD ,FLT1CLM_RPTG_1_CD ,FLT1CLM_RPTG_2_CD ,FLT1CLM_RPTG_3_CD ,FLT1EMP_NBR ,FLT1PLAN_GRP_ID ,FLT1CDHP_CTGRY_CD ,FLT1MBR_NTWK_ID ,PRMRY_CVRG_CD ,MEDCR_CD ,FLT1CII_RMM_FLG );

join(df_RLTNSHPas(RLTNSHP), RLTNSHPACCT_ID == SCDSCD_ORG_ID);

where(trim(SCDSCD_ORG_TYPE_CD)==WAC);

where(SCDRLTD_SCD_ORG_TYPE_CDisin(GRP,CLNT,ASSN));

(trim(SCDRLTD_SCD_ORG_SOR_CD)as(RLTD_SCD_ORG_SOR_CD),trim(SCDRLTD_SCD_ORG_ID)as(RLTD_SCD_ORG_ID), trim(SCDSCD_ORG_ID)as(SCD_ORG_ID),trim(SCDRLTD_SCD_ORG_TYPE_CD)as(RLTD_SCD_ORG_TYPE_CD));

Y);

( F3SGMNTN_ASSN_ID ,F3SGMNTN_CLNT_ID ,F3SGMNTN_GRP_ID ,F3SGMNTN_SUBGRP_ID ,F3EMPLR_DEPT_NBR ,F3FULLY_INSRD_CD ,F3GRP_STTS_CD ,F3HLTH_PROD_SRVC_TYPE_CD ,F3prod_id1as(prod_id);

Y)( F3SGMNTN_ASSN_ID ,F3SGMNTN_CLNT_ID ,F3SGMNTN_GRP_ID ,F3SGMNTN_SUBGRP_ID ,F3EMPLR_DEPT_NBR ,F3FULLY_INSRD_CD ,F3GRP_STTS_CD ,F3HLTH_PROD_SRVC_TYPE_CD ,F3prod_id1as(prod_id);

Y)( F3SGMNTN_ASSN_ID ,F3SGMNTN_CLNT_ID ,F3SGMNTN_GRP_ID ,F3SGMNTN_SUBGRP_ID ,F3EMPLR_DEPT_NBR ,F3FULLY_INSRD_CD ,F3GRP_STTS_CD ,F3HLTH_PROD_SRVC_TYPE_CD ,F3prod_id1as(prod_id);

srgACCT_ID,left_outer);

(F4ACCT_ID ,F4SGMNTN_ASSN_ID ,F4SGMNTN_CLNT_ID ,F4SGMNTN_GRP_ID ,F4SGMNTN_SUBGRP_ID ,F4EMPLR_DEPT_NBR ,F4FULLY_INSRD_CD ,F4GRP_STTS_CD ,F4HLTH_PROD_SRVC_TYPE_CD ,ORIG_HLTH_PROD_SRVC_TYPE_CD ,when(F4prod_idisin(,~01,~02,~03,~NA,~DV,UNK) || F4prod_idisNull,NA)otherwise(upper(trim(regexp_replace(F4prod_id,\\^, \\s))))as(prod_id);

CIIUtilitiesreadDFfromS3(aDataSrcCfg, FRAME5_combined_new);

(F4ACCT_ID ,F4SGMNTN_ASSN_ID ,F4SGMNTN_CLNT_ID ,F4SGMNTN_GRP_ID ,F4SGMNTN_SUBGRP_ID ,F4EMPLR_DEPT_NBR ,F4FULLY_INSRD_CD ,F4GRP_STTS_CD ,F4HLTH_PROD_SRVC_TYPE_CD ,ORIG_HLTH_PROD_SRVC_TYPE_CD ,F4prod_id ,F4PLAN_ID ,F4SGMNTN_SOR_CD ,RPTG_OFSHR_ACSBL_IND ,SCRTY_LVL_CD ,mbr_key ,elgblty_clndr_mnth_end_dt ,mbrshp_sor_cd ,src_grp_nbr ,rltd_prchsr_org_nbr ,prchsr_org_nbr ,fundg_cf_cd ,prod_sor_cd ,prod_id_fltr ,bnft_pkg_id ,pkg_nbr ,mdcl_mbr_cvrg_cnt ,vsn_mbr_cnt ,dntl_mbr_cnt ,mbr_prod_enrlmnt_efctv_dt ,mbr_prod_enrlmnt_trmntn_dt ,cntrct_type_cd ,othr_insrnc_type_cd ,gndr_cd ,mbr_mnth_cob_cd ,prcp_id ,prcp_ctgry_cd ,bnft_pkg_key ,rltd_prchsr_org_type_cd ,prcp_type_cd ,hc_id ,sbscrbr_id ,scrty_lvl_cd_fltr ,prod_ofrg_key ,mdcl_expsr_nbr ,phrmcy_mbr_expsr_nbr ,dntl_expsr_nbr ,vsn_expsr_nbr ,MAX_FUNDG_CF_CD ,PHRMCY_MBR_CVRG_CNT ,hc_idas(hcid_key);

(lit(NA)as(ACCT_ID);

CIIUtilitiesreadDFfromS3(aDataSrcCfg,FRAME6);

